// labels.js — every user-facing string lives here. Swap or edit this file to translate the app.
// [provisional] wording — adjust freely; nothing else needs to change.
window.LABELS = {
  appName: "Flight in the Air",
  tabs: { trips: "Trips", stats: "Stats", settings: "Settings" },

  trips: {
    upcoming: "Upcoming",
    past: "Past",
    empty: "No flights yet.\nTap + to add your first flight.",
    addFlight: "Add flight",
    stages: ["CHECK-IN", "BOARDING", "TAKEOFF", "LANDING"],
    countdown: {
      checkin: "CHECK-IN OPENS IN",
      boarding: "BOARDING IN",
      takeoff: "TAKEOFF IN",
      landing: "LANDING IN",
      landed: "LANDED",
    },
    nextDay: "+1",
  },

  status: {
    planned: "Planned",
    ticketed: "Ticketed",
    "checked-in": "Checked-in",
    flown: "Flown",
    cancelled: "Cancelled",
  },

  detail: {
    newTitle: "New Flight",
    editTitle: "Flight",
    flightNo: "Flight number",
    flightNoPh: "e.g. JX002",
    airline: "Airline",
    date: "Departure date",
    from: "From (IATA)",
    to: "To (IATA)",
    depTime: "Departs (local)",
    arrTime: "Arrives (local)",
    arrDate: "Arrival date",
    depTerminal: "Dep terminal",
    depGate: "Dep gate",
    arrTerminal: "Arr terminal",
    arrGate: "Arr gate",
    status: "Status",
    pnr: "Booking ref (PNR)",
    seat: "Seat",
    cabin: "Cabin",
    cabins: { "": "—", economy: "Economy", premium: "Premium", business: "Business", first: "First" },
    passenger: "Passenger",
    aircraft: "Aircraft",
    notes: "Notes",
    save: "Save",
    cancel: "Cancel",
    delete: "Delete flight",
    deleteConfirm: "Delete this flight? (kept in the database as deleted)",
    exportIcs: "Export .ics",
    syncCalendar: "Sync to Google Calendar",
    fetchInfo: "Fetch flight data",
    fetching: "Fetching…",
    fetchNoBackend: "Set up the backend in Settings first.",
    fetchNotFound: "Schedule not yet published for this date.",
    fetchQuota: "Live data unavailable (quota) — showing saved times.",
    fetchApplied: "Flight data applied — review and save.",
    unknownAirport: "Unknown IATA code",
    invalid: "Please fill flight number, airports, date and times.",
    invalidTimes: "Arrival must be after departure — check the arrival date (+1 day for overnight flights).",
    distance: "Distance",
    duration: "Duration",
    synced: "Synced to Google Calendar.",
    syncFailed: "Calendar sync failed",
  },

  stats: {
    title: "Statistics",
    includeUpcoming: "Include upcoming flights",
    flights: "Flights",
    hours: "Hours",
    km: "Kilometers",
    airports: "Airports",
    airlines: "Airlines",
    countries: "Countries",
    aroundWorld: "× around the world",
    topAirlines: "Top airlines",
    topAirports: "Top airports",
    topRoutes: "Top routes",
    empty: "No flights to count yet.",
  },

  settings: {
    title: "Settings",
    backendSection: "Backend",
    backendUrl: "Apps Script URL (/exec)",
    token: "API token",
    testConnection: "Test connection",
    testing: "Testing…",
    testOkLocal: "No backend configured — running in on-device mode.",
    testOk: "Connected — {n} flights in cloud database.",
    testFail: "Connection failed",
    saveBackend: "Save & sync",
    calendarSection: "Calendar (PRO)",
    calendarHint: "Primary: sync to a dedicated “Flights” Google Calendar, then enable it on your iPhone. It updates automatically.",
    syncAll: "Sync all flights to Google Calendar",
    copyFeed: "Copy ICS feed URL",
    feedCopied: "Feed URL copied.",
    exportAll: "Export all flights (.ics)",
    importSection: "Import",
    importIcs: "Import .ics file",
    importJson: "Bulk import JSON",
    importJsonPh: "Paste a JSON array of flights…",
    importPreview: "Preview",
    importConfirm: "Import {n} flights",
    importDone: "Imported: {c} created, {u} updated.",
    importNone: "No flight events found in this file.",
    telegramSection: "Notifications",
    testTelegram: "Send test Telegram message",
    telegramSent: "Test message sent.",
    aboutSection: "About",
    version: "Version",
    checkUpdate: "Check for update",
    updateBanner: "Update available — tap to reload",
    offlineBadge: "Offline — data as of {t}",
    pendingBadge: "{n} changes waiting to sync",
    localMode: "On-device mode (no backend)",
  },

  common: {
    ok: "OK",
    error: "Something went wrong",
    copied: "Copied.",
    loading: "Loading…",
  },
};
